[project]
name = "vsi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "django>=5.2.7",
    "dotenv>=0.9.9",
    "psycopg2-binary>=2.9.11",
]
